name: numeris
description: "opennumeris"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.1.0
  flutter_svg: ^2.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  just_the_tooltip: ^0.0.12
  vibration: ^3.1.4
  shared_preferences: ^2.5.3
  flutter_styled_toast: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/UI/
  fonts:
    - family: "poppins-medium"
      fonts:
        - asset: assets/fonts/poppins-medium.ttf
    - family: "poppins-bold"
      fonts:
        - asset: assets/fonts/poppins-bold.ttf

# personalizar Ã­cones em flutter_launcher_icons.yaml - devido a um bug da dependencia

# personalizar splash screen
flutter_native_splash:
  color: "#EAEAEA"
  color_dark: "#EAEAEA"
  image: assets/UI/icons/icon_splash.png
  android_12:
    image: assets/UI/icons/icon_splash_12.png
    image_dark: assets/UI/icons/icon_splash_12.png
    icon_background_color_dark: "#FFFFFF"
    icon_background_color: "#FFFFFF"